---
- hosts: all
  gather_facts: true
  any_errors_fatal: true #stop at first error
  user: root
  become: True
  vars:
    etc_shadow_logs: "{{ ansible_hostname }}-log_etc_shadow.txt"

  tasks:
  - name: Set variables
    set_fact:
     remote_dir: "/tmp/etc_shadow"
     bastion_dir: "/tmp/etc_shadow_logs/"

  - name: Create directory to place /etc/shadow logs
    file:
      path: "{{ remote_dir }}"
      state: directory
      owner: root
      group: root

    register: response

  - name: Get Copy file /etc/shadow
    shell: "cat /etc/shadow >> /tmp/etc_shadow/$HOSTNAME-log_etc_shadow.txt"

  - name: Copy files to servers to Bastion
    fetch:
       src: "{{ remote_dir }}/{{ etc_shadow_logs }}"
       dest: "{{ bastion_dir }}"
       flat: yes
    register: response

  - name: Show response
    debug: msg="{{ response }}"
...
